# Generated by Django 5.0.6 on 2025-04-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_alter_myusers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='phone',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
