# Generated by Django 5.0.6 on 2025-03-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_product_image_3'),
    ]

    operations = [
    ]
