# Generated by Django 5.0.6 on 2025-03-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_auto_20250317_0005'),
    ]

    operations = [
    ]
